<script>
    function ConfirmDelete()
    {
        var x = confirm("Are you sure you want to delete?");
        if (x)
            return true;
        else
            return false;
    }
</script>
<p>
<?php echo __("Please note that before deleting a customer account, all associated information will be permanently erased and cannot be recovered under any circumstances.");
?>
</p>
<form action="<?php echo $block->getBaseUrl()?>removeaccount/index/remove" method="post">
    <button class="action primary" onclick="return ConfirmDelete();" type="submit" name="actiondelete" value="1">Delete Customer</button>
</form>